name: yaldi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  dio: ^5.9.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  auto_size_text: ^3.0.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  provider: ^6.1.4
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  loading_animation_widget: ^1.3.0
  dartz: ^0.10.1
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/core/env/

  fonts:
    - family: Messiri
      fonts:
        - asset: assets/fonts/Messiri/ElMessiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Messiri/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/Messiri/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Messiri/ElMessiri-Bold.ttf
          weight: 700
